"""add_parse_job_diff_fields

Revision ID: b78a064c34a9
Revises: f3c1a2d4e6b8
Create Date: 2026-06-10 23:56:06.488971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b78a064c34a9'
down_revision: Union[str, Sequence[str], None] = 'f3c1a2d4e6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parse_jobs', sa.Column('diff_mode', sa.Boolean(), nullable=False))
    op.add_column('parse_jobs', sa.Column('diff_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parse_jobs', 'diff_data')
    op.drop_column('parse_jobs', 'diff_mode')
    # ### end Alembic commands ###
